In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
from sklearn import datasets, linear_model
from scipy import linalg

In [3]:
bhdata = datasets.load_boston()

featuredata = bhdata.data

colnames = bhdata.feature_names

data = pd.DataFrame(featuredata,columns=colnames)
data['target'] = bhdata.target

In [4]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [5]:
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.593761   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.596783   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.647423   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT      target  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [6]:
#split the dataset into training and testig 
data_train, data_test = train_test_split(data,test_size=0.30,random_state=707)

In [7]:
data_train.index, data_test.index

(Int64Index([171, 215,  79, 240,  29, 393, 308, 381,  35,  48,
             ...
              45, 442, 205,  39, 300, 121, 355, 159, 249, 347],
            dtype='int64', length=354),
 Int64Index([  6, 487, 259, 128, 199, 361, 396, 192, 408, 349,
             ...
             207, 410, 453, 131, 212,  51, 168,  59, 278, 326],
            dtype='int64', length=152))

In [8]:
data_train.index, data_test.index

(Int64Index([171, 215,  79, 240,  29, 393, 308, 381,  35,  48,
             ...
              45, 442, 205,  39, 300, 121, 355, 159, 249, 347],
            dtype='int64', length=354),
 Int64Index([  6, 487, 259, 128, 199, 361, 396, 192, 408, 349,
             ...
             207, 410, 453, 131, 212,  51, 168,  59, 278, 326],
            dtype='int64', length=152))

In [9]:
data_train.shape,data_test.shape

((354, 14), (152, 14))

In [10]:
corr = data.corr()
corr

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.199458  0.404471 -0.055295  0.417521 -0.219940  0.350784   
ZN      -0.199458  1.000000 -0.533828 -0.042697 -0.516604  0.311991 -0.569537   
INDUS    0.404471 -0.533828  1.000000  0.062938  0.763651 -0.391676  0.644779   
CHAS    -0.055295 -0.042697  0.062938  1.000000  0.091203  0.091251  0.086518   
NOX      0.417521 -0.516604  0.763651  0.091203  1.000000 -0.302188  0.731470   
RM      -0.219940  0.311991 -0.391676  0.091251 -0.302188  1.000000 -0.240265   
AGE      0.350784 -0.569537  0.644779  0.086518  0.731470 -0.240265  1.000000   
DIS     -0.377904  0.664408 -0.708027 -0.099176 -0.769230  0.205246 -0.747881   
RAD      0.622029 -0.311948  0.595129 -0.007368  0.611441 -0.209847  0.456022   
TAX      0.579564 -0.314563  0.720760 -0.035587  0.668023 -0.292048  0.506456   
PTRATIO  0.288250 -0.391679  0.383248 -0.121515  0.188933 -0.355501  0.261515   
B       -0.377365  0.175520 -0.356977  0.048788 -0.380051  0.128069 -0.273534   
LSTAT    0.452220 -0.412995  0.603800 -0.053929  0.590879 -0.613808  0.602339   
target  -0.385832  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   

              DIS       RAD       TAX   PTRATIO         B     LSTAT    target  
CRIM    -0.377904  0.622029  0.579564  0.288250 -0.377365  0.452220 -0.385832  
ZN       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445  
INDUS   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725  
CHAS    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260  
NOX     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321  
RM       0.205246 -0.209847 -0.292048 -0.355501  0.128069 -0.613808  0.695360  
AGE     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955  
DIS      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929  
RAD     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626  
TAX     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536  
PTRATIO -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787  
B        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461  
LSTAT   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663  
target   0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000

In [11]:
XTrain = np.array(data_train.iloc[:,0:(data.shape[1]-1)])
YTrain = np.array(data_train['target'])

In [12]:
XTest = np.array(data_test.iloc[:,0:(data.shape[1]-1)])
YTest = np.array(data_test['target'])

In [13]:
XTrain.shape, XTest.shape

((354, 13), (152, 13))

In [14]:
#multiple linear regression model
reg = linear_model.LinearRegression(normalize=True)
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [15]:
reg.fit(XTrain,YTrain) #training the model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [16]:
print('Coefficients: \n', np.round(reg.coef_,0))

Coefficients: 
 [ -0.   0.   0.   3. -20.   4.   0.  -1.   0.  -0.  -1.   0.  -1.]


In [17]:
print('Coefficients: \n', np.round(reg.intercept_,0))

Coefficients: 
 37.0


In [18]:
reg.score(XTrain,YTrain) # R-square value from the trained model

0.7389945898859912

In [19]:
reg.score(XTest,YTest) # R-square value from the test set

0.72688867614350339

In [20]:
from scipy import stats

In [21]:
#adjusted R square
def AdjustedRSquare(model,X,Y):
    YHat = model.predict(X)
    n,k = X.shape
    sse = np.sum(np.square(YHat-Y),axis=0)
    sst = np.sum(np.square(Y-np.mean(Y)),axis=0)
    R2 = 1- sse/sst
    adjR2 = R2-(1-R2)*(float(k)/(n-k-1))
    return adjR2, R2

In [22]:
def ReturnPValue(model,X,Y):
    YHat = model.predict(X)
    n,k = X.shape
    sse = np.sum(np.square(YHat-Y),axis=0)
    x = np.hstack((np.ones((n,1)),np.matrix(X)))
    df = float(n-k-1)
    sampleVar = sse/df
    sampleVarianceX = x.T*x
    covarianceMatrix = linalg.sqrtm(sampleVar*sampleVarianceX.I)
    se = covarianceMatrix.diagonal()[1:]
    betasTstat = np.zeros(len(se))
    for i in range(len(se)):
        betasTstat[i] = model.coef_[i]/se[i]
    betasPvalue = 1- stats.t.cdf(abs(betasTstat),df)
    return betasPvalue

In [23]:
np.round(ReturnPValue(reg,XTrain,YTrain),2)

array([ 0.01,  0.  ,  0.25,  0.  ,  0.  ,  0.  ,  0.23,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ])

In [24]:
reg.adjR2, reg.R2 = AdjustedRSquare(reg,XTrain,YTrain)
print (reg.adjR2, reg.R2)


0.729014971264 0.738994589886


In [25]:
def ErrorMetric(model,X,Y):
    Yhat = model.predict(X)
    MAPE = np.mean(abs(Y-Yhat)/Y)*100
    MSSE = np.mean(np.square(Y-Yhat))
    return MAPE, MSSE

In [26]:
ErrorMetric(reg,XTrain,YTrain)

(17.106566686167696, 23.834191770849749)

In [27]:
ErrorMetric(reg,XTest,YTest)

(17.864279853548172, 18.456930882079579)

In [28]:
alpha = 0.05
erroR = 1

In [29]:
reg.BetasPValue = ReturnPValue(reg,XTrain,YTrain)

In [30]:
MAPE, prevMSSE = ErrorMetric(reg,XTest,YTest)
MAPE, prevMSSE

(17.864279853548172, 18.456930882079579)

In [31]:
while (erroR > 0.001):
    ind = np.where(reg.BetasPValue>alpha)[0]
    if(len(ind)==0):
        ind = np.argmax(reg.BetasPValue)
        
    XTrain = np.delete(XTrain,ind,axis=1)
    XTest = np.delete(XTest,ind,axis=1)
    
    reg.fit(XTrain,YTrain)
    
    reg.BetasPValue = ReturnPValue(reg,XTrain, YTrain)
    MAPE, MSSE = ErrorMetric(reg,XTest,YTest)

    erroR = prevMSSE - MSSE
print (erroR, MSSE)

-0.754216389765 19.2111472718


In [32]:
np.round(reg.score(XTrain,YTrain),2)

0.72999999999999998

In [33]:
np.round(reg.score(XTest,YTest),2)

0.71999999999999997

In [34]:
np.round(AdjustedRSquare(reg,XTrain,YTrain),2)

array([ 0.73,  0.73])

In [35]:
np.round(AdjustedRSquare(reg,XTest,YTest),2)

array([ 0.7 ,  0.72])

In [36]:
np.round(reg.coef_,1)

array([  0. ,   3.4, -17.9,   4.1,  -1.4,   0.3,  -0. ,  -1. ,   0. ,  -0.5])

In [37]:
np.round(reg.intercept_,1)

36.799999999999997

In [38]:
len(reg.coef_)

10

# Next Class

In [39]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [43]:
data.RAD.value_counts()

24.0    132
5.0     115
4.0     110
3.0      38
6.0      26
8.0      24
2.0      24
1.0      20
7.0      17
Name: RAD, dtype: int64

In [44]:
RAD_Dummies = pd.get_dummies(data.RAD,prefix='RAD',drop_first=True)

In [45]:
RAD_Dummies.head(10)

RAD_2.0  RAD_3.0  RAD_4.0  RAD_5.0  RAD_6.0  RAD_7.0  RAD_8.0  RAD_24.0
0        0        0        0        0        0        0        0         0
1        1        0        0        0        0        0        0         0
2        1        0        0        0        0        0        0         0
3        0        1        0        0        0        0        0         0
4        0        1        0        0        0        0        0         0
5        0        1        0        0        0        0        0         0
6        0        0        0        1        0        0        0         0
7        0        0        0        1        0        0        0         0
8        0        0        0        1        0        0        0         0
9        0        0        0        1        0        0        0         0

In [46]:
modeldata = pd.concat([data,RAD_Dummies],axis=1)

In [47]:
modeldata.head(2)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   

     ...     LSTAT  target  RAD_2.0  RAD_3.0  RAD_4.0  RAD_5.0  RAD_6.0  \
0    ...      4.98    24.0        0        0        0        0        0   
1    ...      9.14    21.6        1        0        0        0        0   

   RAD_7.0  RAD_8.0  RAD_24.0  
0        0        0         0  
1        0        0         0  

[2 rows x 22 columns]

In [49]:
from sklearn.model_selection import train_test_split

In [52]:
df_train, df_test = train_test_split(modeldata,test_size=0.30,random_state=10001)

In [53]:
df_train.shape, df_test.shape

((354, 22), (152, 22))

In [57]:
import sklearn as sk
sk.__version__

'0.19.1'

In [58]:
XTrain = df_train.iloc[:,list(range(7)) + list(range(9,13)) + list(range(15,df_train.shape[1]))].as_matrix()
YTrain = df_train['target']

In [59]:
XTest = df_test.iloc[:,list(range(7)) + list(range(9,13)) + list(range(15,df_test.shape[1]))].as_matrix()
YTest = df_test['target']

In [60]:
XTrain.shape,YTrain.shape

((354, 18), (354,))

In [61]:
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [62]:
regr = linear_model.LinearRegression(normalize=True)

In [63]:
regr.fit(XTrain,YTrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [64]:
regr.score(XTrain,YTrain) # training accuracy 73.5%

0.7349694247908396

In [65]:
regr.score(XTest,YTest) # test accuracy 64.2%

0.64205827377551983

In [66]:
regr.MAPE, regr.MSSE = ErrorMetric(regr,XTest,YTest)
regr.MAPE, regr.MSSE

(17.00989073130371, 31.841539140093694)

In [67]:
regr.adjR2, regr.R2 = AdjustedRSquare(regr,XTrain,YTrain)
print (regr.adjR2, regr.R2)

0.7207289759736312 0.7349694247908398


In [68]:
# Polynomial features
# We can try Polynomial Rergession 
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler

In [69]:
scaler = StandardScaler()

In [70]:
X = scaler.fit_transform(bhdata['data'])

In [71]:
pd.DataFrame(X).head()

0         1         2         3         4         5         6   \
0 -0.417713  0.284830 -1.287909 -0.272599 -0.144217  0.413672 -0.120013   
1 -0.415269 -0.487722 -0.593381 -0.272599 -0.740262  0.194274  0.367166   
2 -0.415272 -0.487722 -0.593381 -0.272599 -0.740262  1.282714 -0.265812   
3 -0.414680 -0.487722 -1.306878 -0.272599 -0.835284  1.016303 -0.809889   
4 -0.410409 -0.487722 -1.306878 -0.272599 -0.835284  1.228577 -0.511180   

         7         8         9         10        11        12  
0  0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.075562  
1  0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.492439  
2  0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.208727  
3  1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.361517  
4  1.077737 -0.752922 -1.106115  0.113032  0.441052 -1.026501

In [72]:
poly = PolynomialFeatures(2)

In [73]:
poly

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False)

In [74]:
Xpoly = poly.fit_transform(X)

In [75]:
Xpoly.shape

(506, 105)

In [76]:
print (len(Xpoly))

506


In [77]:
x = Xpoly
Y = bhdata['target']

In [78]:
x

array([[ 1.        , -0.41771335,  0.28482986, ...,  0.19452681,
        -0.47437883,  1.15683427],
       [ 1.        , -0.41526932, -0.48772236, ...,  0.19452681,
        -0.21719133,  0.24249653],
       [ 1.        , -0.41527165, -0.48772236, ...,  0.15715436,
        -0.47917217,  1.46102192],
       ..., 
       [ 1.        , -0.41137448, -0.48772236, ...,  0.19452681,
        -0.43357505,  0.9663826 ],
       [ 1.        , -0.40568883, -0.48772236, ...,  0.16259032,
        -0.34891116,  0.74874691],
       [ 1.        , -0.41292893, -0.48772236, ...,  0.19452681,
        -0.29508947,  0.44763905]])

In [79]:
# interaction features
featurenames = ['intercept'] + list(bhdata['feature_names'])

polyfeaturenames = [];

for i,x in enumerate(featurenames):
    for y in featurenames[i:]:
        if (x == 'intercept'):
            polyfeaturenames.append(y)
        elif (x==y):
            polyfeaturenames.append((y+'_Square'))
        else:
            polyfeaturenames.append((x+'_'+y))

print(featurenames)


['intercept', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']


In [80]:
print (polyfeaturenames)

['intercept', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'CRIM_Square', 'CRIM_ZN', 'CRIM_INDUS', 'CRIM_CHAS', 'CRIM_NOX', 'CRIM_RM', 'CRIM_AGE', 'CRIM_DIS', 'CRIM_RAD', 'CRIM_TAX', 'CRIM_PTRATIO', 'CRIM_B', 'CRIM_LSTAT', 'ZN_Square', 'ZN_INDUS', 'ZN_CHAS', 'ZN_NOX', 'ZN_RM', 'ZN_AGE', 'ZN_DIS', 'ZN_RAD', 'ZN_TAX', 'ZN_PTRATIO', 'ZN_B', 'ZN_LSTAT', 'INDUS_Square', 'INDUS_CHAS', 'INDUS_NOX', 'INDUS_RM', 'INDUS_AGE', 'INDUS_DIS', 'INDUS_RAD', 'INDUS_TAX', 'INDUS_PTRATIO', 'INDUS_B', 'INDUS_LSTAT', 'CHAS_Square', 'CHAS_NOX', 'CHAS_RM', 'CHAS_AGE', 'CHAS_DIS', 'CHAS_RAD', 'CHAS_TAX', 'CHAS_PTRATIO', 'CHAS_B', 'CHAS_LSTAT', 'NOX_Square', 'NOX_RM', 'NOX_AGE', 'NOX_DIS', 'NOX_RAD', 'NOX_TAX', 'NOX_PTRATIO', 'NOX_B', 'NOX_LSTAT', 'RM_Square', 'RM_AGE', 'RM_DIS', 'RM_RAD', 'RM_TAX', 'RM_PTRATIO', 'RM_B', 'RM_LSTAT', 'AGE_Square', 'AGE_DIS', 'AGE_RAD', 'AGE_TAX', 'AGE_PTRATIO', 'AGE_B', 'AGE_LSTAT', 'DIS_Square', 'DIS_RAD', 'DIS_TAX', 'DIS_PTR

In [81]:
Xpoly.shape

(506, 105)

In [82]:
regr2 = linear_model.LinearRegression(normalize=True)

regr2

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [83]:
regr2.fit(Xpoly,Y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [84]:
regr2.score(Xpoly,Y)

0.92914629705575003

In [85]:
regr2.adjR2, regr2.R2 = AdjustedRSquare(regr2,Xpoly,Y)
print (regr2.adjR2, regr2.R2)


0.910547200033 0.929146297056


In [87]:
regr2.MAPE, regr2.MSSE = ErrorMetric(regr2,Xpoly,Y)
print (regr2.MAPE, regr2.MSSE)

9.37184182932 5.98143815457


In [90]:
print (np.round(regr.coef_,2))
print (np.round(regr2.coef_,0))

[-0.08  0.01  0.12 -0.12 -6.1   4.82  0.02 -0.01 -1.11  0.01 -0.46  4.08
  2.44  1.97  1.64  3.11  4.37  6.84]
[  0.00000000e+00   1.60000000e+01   1.50000000e+01   9.00000000e+00
  -1.53264039e+12  -2.00000000e+00   4.00000000e+00  -2.00000000e+00
  -3.00000000e+00   5.00000000e+00  -1.00000000e+01   1.00000000e+00
   1.00000000e+00  -3.00000000e+00   0.00000000e+00   4.30000000e+01
   2.30000000e+01   5.00000000e+00  -1.00000000e+00   1.00000000e+00
  -1.00000000e+00  -2.00000000e+00   1.60000000e+01  -3.50000000e+01
   7.00000000e+00  -0.00000000e+00   1.00000000e+00  -0.00000000e+00
  -1.00000000e+00  -0.00000000e+00  -3.00000000e+00   0.00000000e+00
   0.00000000e+00  -1.00000000e+00  -1.00000000e+00   2.00000000e+00
  -0.00000000e+00   1.00000000e+00  -1.00000000e+00   2.00000000e+00
   0.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
   2.00000000e+00  -1.00000000e+00   1.00000000e+00  -0.00000000e+00
   2.00000000e+00  -1.00000000e+00   4.51334210e+11  -1.00000

In [110]:
# Null: beta estimates are = 0
# Alt : beta estimates are != 0

In [111]:
# to restrict the model overfitting
# regularized regression models

# LASSO - L1
# Ridge - L2

In [91]:
from sklearn.linear_model import Lasso

In [93]:
XTrain, XTest, YTrain, YTest = train_test_split(Xpoly,Y, test_size=0.25,random_state=1234)

In [94]:
XTrain.shape, XTest.shape, YTrain.shape, YTest.shape

((379, 105), (127, 105), (379,), (127,))

In [110]:
lassoMod = Lasso(alpha=4.0)

In [111]:
lassoMod.fit(XTrain,YTrain)

Lasso(alpha=4.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [112]:
print (lassoMod.coef_)

[ 0.         -0.          0.         -0.          0.         -0.
  0.08778137 -0.          0.         -0.         -0.         -0.          0.
 -1.92138849 -0.05487952 -0.         -0.          0.         -0.         -0.
 -0.          0.         -0.         -0.         -0.          0.         -0.
  0.21605379 -0.          0.         -0.          0.         -0.          0.
 -0.         -0.         -0.          0.         -0.          0.          0.
 -0.         -0.         -0.          0.         -0.         -0.          0.
  0.         -0.          0.06046166 -0.          0.          0.         -0.
  0.          0.          0.          0.         -0.         -0.         -0.
 -0.          0.         -0.         -0.          0.          0.         -0.
  0.4093829  -0.         -0.         -0.         -0.         -0.          0.
 -0.          0.         -0.         -0.         -0.         -0.          0.
 -0.         -0.          0.          0.          0.         -0.          0.
 -0.       

In [113]:
lassoMod.coef_[((lassoMod.coef_)!=0)]

array([ 0.08778137, -1.92138849, -0.05487952,  0.21605379,  0.06046166,
        0.4093829 , -0.26857829])

In [117]:
lassoMod = Lasso(alpha=2.0)
lassoMod.fit(XTrain,YTrain)
print (lassoMod.coef_)

[ 0.         -0.          0.         -0.          0.         -0.
  1.17026498 -0.          0.         -0.         -0.         -0.09892521
  0.         -3.19789261 -0.07078692  0.         -0.          0.         -0.
 -0.         -0.          0.         -0.         -0.          0.          0.
 -0.          0.15665256 -0.          0.         -0.          0.         -0.
  0.         -0.         -0.         -0.          0.         -0.          0.
  0.         -0.         -0.         -0.          0.         -0.         -0.
  0.          0.         -0.          0.15429983 -0.          0.          0.
 -0.          0.          0.          0.          0.         -0.         -0.
 -0.         -0.          0.         -0.         -0.         -0.          0.
 -0.          0.72977841 -0.          0.         -0.         -0.
 -0.59164056  0.         -0.          0.          0.         -0.         -0.
 -0.          0.         -0.         -0.          0.          0.          0.
 -0.          0.         -0

In [118]:
lassoMod.coef_[((lassoMod.coef_)!=0)]

array([ 1.17026498, -0.09892521, -3.19789261, -0.07078692,  0.15665256,
        0.15429983,  0.72977841, -0.59164056, -0.28246009])

In [119]:
names = [polyfeaturenames[i] for i in list(np.where(lassoMod.coef_ != 0.0)[0])]
names

['RM',
 'PTRATIO',
 'LSTAT',
 'CRIM_Square',
 'ZN_Square',
 'CHAS_Square',
 'RM_Square',
 'RM_PTRATIO',
 'B_Square']

In [120]:
lassoMod.MAPE, lassoMod.MSSE = ErrorMetric(lassoMod, XTrain, YTrain)

In [121]:
print (lassoMod.MAPE, lassoMod.MSSE)

17.7695907132 26.0286858573


In [122]:
lassoMod.MAPE, lassoMod.MSSE = ErrorMetric(lassoMod, XTest, YTest)

In [123]:
print (lassoMod.MAPE, lassoMod.MSSE)

22.9368193638 30.5748152886


In [124]:
from sklearn.linear_model import Ridge

In [125]:
ridgeMod1 = Ridge(alpha=1)
ridgeMod1.fit(XTrain,YTrain)
names = [polyfeaturenames[i] for i in list(np.where(ridgeMod1.coef_ != 0.0)[0])]
print(names)
ridgeMod1.MAPE, ridgeMod1.MSSE = ErrorMetric(ridgeMod1, XTrain, YTrain)
print (ridgeMod1.MAPE, ridgeMod1.MSSE)


['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'CRIM_Square', 'CRIM_ZN', 'CRIM_INDUS', 'CRIM_CHAS', 'CRIM_NOX', 'CRIM_RM', 'CRIM_AGE', 'CRIM_DIS', 'CRIM_RAD', 'CRIM_TAX', 'CRIM_PTRATIO', 'CRIM_B', 'CRIM_LSTAT', 'ZN_Square', 'ZN_INDUS', 'ZN_CHAS', 'ZN_NOX', 'ZN_RM', 'ZN_AGE', 'ZN_DIS', 'ZN_RAD', 'ZN_TAX', 'ZN_PTRATIO', 'ZN_B', 'ZN_LSTAT', 'INDUS_Square', 'INDUS_CHAS', 'INDUS_NOX', 'INDUS_RM', 'INDUS_AGE', 'INDUS_DIS', 'INDUS_RAD', 'INDUS_TAX', 'INDUS_PTRATIO', 'INDUS_B', 'INDUS_LSTAT', 'CHAS_Square', 'CHAS_NOX', 'CHAS_RM', 'CHAS_AGE', 'CHAS_DIS', 'CHAS_RAD', 'CHAS_TAX', 'CHAS_PTRATIO', 'CHAS_B', 'CHAS_LSTAT', 'NOX_Square', 'NOX_RM', 'NOX_AGE', 'NOX_DIS', 'NOX_RAD', 'NOX_TAX', 'NOX_PTRATIO', 'NOX_B', 'NOX_LSTAT', 'RM_Square', 'RM_AGE', 'RM_DIS', 'RM_RAD', 'RM_TAX', 'RM_PTRATIO', 'RM_B', 'RM_LSTAT', 'AGE_Square', 'AGE_DIS', 'AGE_RAD', 'AGE_TAX', 'AGE_PTRATIO', 'AGE_B', 'AGE_LSTAT', 'DIS_Square', 'DIS_RAD', 'DIS_TAX', 'DIS_PTRATIO', 'DIS_B

In [126]:
ridgeMod1 = Ridge(alpha=0)
ridgeMod1.fit(XTrain,YTrain)
names = [polyfeaturenames[i] for i in list(np.where(ridgeMod1.coef_ != 0.0)[0])]
print(names)
ridgeMod1.MAPE, ridgeMod1.MSSE = ErrorMetric(ridgeMod1, XTrain, YTrain)
print (ridgeMod1.MAPE, ridgeMod1.MSSE)


['intercept', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'CRIM_Square', 'CRIM_ZN', 'CRIM_INDUS', 'CRIM_CHAS', 'CRIM_NOX', 'CRIM_RM', 'CRIM_AGE', 'CRIM_DIS', 'CRIM_RAD', 'CRIM_TAX', 'CRIM_PTRATIO', 'CRIM_B', 'CRIM_LSTAT', 'ZN_Square', 'ZN_INDUS', 'ZN_CHAS', 'ZN_NOX', 'ZN_RM', 'ZN_AGE', 'ZN_DIS', 'ZN_RAD', 'ZN_TAX', 'ZN_PTRATIO', 'ZN_B', 'ZN_LSTAT', 'INDUS_Square', 'INDUS_CHAS', 'INDUS_NOX', 'INDUS_RM', 'INDUS_AGE', 'INDUS_DIS', 'INDUS_RAD', 'INDUS_TAX', 'INDUS_PTRATIO', 'INDUS_B', 'INDUS_LSTAT', 'CHAS_Square', 'CHAS_NOX', 'CHAS_RM', 'CHAS_AGE', 'CHAS_DIS', 'CHAS_RAD', 'CHAS_TAX', 'CHAS_PTRATIO', 'CHAS_B', 'CHAS_LSTAT', 'NOX_Square', 'NOX_RM', 'NOX_AGE', 'NOX_DIS', 'NOX_RAD', 'NOX_TAX', 'NOX_PTRATIO', 'NOX_B', 'NOX_LSTAT', 'RM_Square', 'RM_AGE', 'RM_DIS', 'RM_RAD', 'RM_TAX', 'RM_PTRATIO', 'RM_B', 'RM_LSTAT', 'AGE_Square', 'AGE_DIS', 'AGE_RAD', 'AGE_TAX', 'AGE_PTRATIO', 'AGE_B', 'AGE_LSTAT', 'DIS_Square', 'DIS_RAD', 'DIS_TAX', 'DIS_PTR

In [127]:
# Hyper-Parameters

#Lasso(alpha=4.0, copy_X=True, fit_intercept=True, max_iter=1000,
 #  normalize=False, positive=False, precompute=False, random_state=None,
  # selection='cyclic', tol=0.0001, warm_start=False)

# Grid Search

# Grid Search + Cross Validation

In [129]:
from sklearn.grid_search import GridSearchCV

In [130]:
XTrain, XTest, YTrain, YTest = train_test_split(Xpoly,Y, test_size=0.25,random_state=1234)

In [131]:
XTrain.shape, XTest.shape, YTrain.shape, YTest.shape

((379, 105), (127, 105), (379,), (127,))

In [132]:
from sklearn.cross_validation import ShuffleSplit

In [133]:
from sklearn.metrics import r2_score

In [134]:
def performance_metric(y_true, y_predict):
    score = r2_score(y_true, y_predict)
    return score

In [135]:
from sklearn.metrics import make_scorer

In [136]:
# Grid Search + Cross Validation Method 
def fit_model(X,y):
    cv_sets = ShuffleSplit(XTrain.shape[0],n_iter=10,test_size=0.20,random_state=1234) # fold selection
    ridgeModel = Ridge() #model initialization
    params = {'alpha':list(range(0,11)), # hyper parameter setting
             'solver' : ('auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga')} 
    scoring_func = make_scorer(performance_metric) # accruracy measure
    grid = GridSearchCV(ridgeModel,params,scoring_func,cv=cv_sets) # grid search
    grid = grid.fit(X,y) # models
    return grid.best_estimator_ # getting best hyperparameters that ensures high accuracy with low std dev

In [137]:
fit_model(XTrain,YTrain)

Ridge(alpha=4, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='lsqr', tol=0.001)

In [138]:
final_model = fit_model(XTrain,YTrain)

In [139]:
ErrorMetric(final_model, XTrain, YTrain)

(9.1600878870230531, 5.9620077469390305)

In [140]:
ErrorMetric(final_model, XTest, YTest)

(13.203533239934503, 10.951006284731381)

In [141]:
regr2.adjR2, regr2.R2 = AdjustedRSquare(final_model, XTrain, YTrain)
print (regr2.adjR2, regr2.R2)

0.89461760529 0.92389049271


In [143]:
regr2.adjR2, regr2.R2 = AdjustedRSquare(final_model, XTest, YTest)
print (regr2.adjR2, regr2.R2)

0.35748714335 0.892914523892


In [144]:
final_model.coef_

array([  0.00000000e+00,  -6.85360371e-02,   1.35368037e-01,
         3.95112906e-01,   1.24432880e-01,  -1.16978485e+00,
         3.02045742e+00,  -1.36966792e+00,  -2.51373192e+00,
         1.21320418e+00,  -1.36033507e+00,  -2.77005010e-01,
         5.29998476e-01,  -3.56129665e+00,   9.86669825e-02,
         1.39348358e-03,   2.06501483e-02,   2.11349134e+00,
        -6.31030866e-01,   8.76126041e-01,   2.07978608e-01,
         1.96216728e-01,  -1.01987925e+00,   2.46482209e-01,
        -3.19047150e-01,  -2.27964516e-01,   5.46084328e-01,
         2.97663782e-02,   1.55442845e-01,   1.11643304e-02,
        -1.85015814e-01,   3.48998028e-01,  -2.58107544e-01,
        -4.18153911e-01,  -3.13598649e-01,   1.45601600e+00,
         1.62365102e-02,   2.68885450e-01,  -4.46822651e-01,
         9.32645277e-01,   5.40696135e-01,   1.35051196e+00,
         6.86542139e-01,   2.91966105e-01,   5.17070798e-01,
         8.34980521e-03,  -5.41322762e-02,  -5.69418151e-01,
         4.66261146e-01,

In [145]:
XTrain.shape

(379, 105)

In [147]:
help(Lasso())

Help on Lasso in module sklearn.linear_model.coordinate_descent object:

class Lasso(ElasticNet)
 |  Linear Model trained with L1 prior as regularizer (aka the Lasso)
 |  
 |  The optimization objective for Lasso is::
 |  
 |      (1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
 |  
 |  Technically the Lasso model is optimizing the same objective function as
 |  the Elastic Net with ``l1_ratio=1.0`` (no L2 penalty).
 |  
 |  Read more in the :ref:`User Guide <lasso>`.
 |  
 |  Parameters
 |  ----------
 |  alpha : float, optional
 |      Constant that multiplies the L1 term. Defaults to 1.0.
 |      ``alpha = 0`` is equivalent to an ordinary least square, solved
 |      by the :class:`LinearRegression` object. For numerical
 |      reasons, using ``alpha = 0`` with the ``Lasso`` object is not advised.
 |      Given this, you should use the :class:`LinearRegression` object.
 |  
 |  fit_intercept : boolean
 |      whether to calculate the intercept for this model. If set
 |    

In [148]:
# Grid Search + Cross Validation Method 
def fit_model(X,y):
    cv_sets = ShuffleSplit(XTrain.shape[0],n_iter=10,test_size=0.20,random_state=1234) # fold selection
    LassoModel = Lasso() #model initialization
    params = {'alpha':list(range(0,11)), # hyper parameter setting
             } 
    scoring_func = make_scorer(performance_metric) # accruracy measure
    grid = GridSearchCV(LassoModel,params,scoring_func,cv=cv_sets) # grid search
    grid = grid.fit(X,y) # models
    return grid.best_estimator_ # getting best hyperparameters that ensures high accuracy with low std dev

In [149]:
fit_model(XTrain,YTrain)

C:\Users\Tcll.Bantd1.TIMESGROUP\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:1675: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Tcll.Bantd1.TIMESGROUP\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:477: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  positive)
C:\Users\Tcll.Bantd1.TIMESGROUP\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\Tcll.Bantd1.TIMESGROUP\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:1675: UserWarning: With alpha=0,

Lasso(alpha=1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [150]:
final_model1 = fit_model(XTrain,YTrain)

C:\Users\Tcll.Bantd1.TIMESGROUP\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:1675: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Tcll.Bantd1.TIMESGROUP\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:477: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  positive)
C:\Users\Tcll.Bantd1.TIMESGROUP\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\Tcll.Bantd1.TIMESGROUP\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:1675: UserWarning: With alpha=0,

In [151]:
regr2.adjR2, regr2.R2 = AdjustedRSquare(final_model1, XTrain, YTrain)
print (regr2.adjR2, regr2.R2)

0.650405136221 0.747514820604


In [152]:
regr2.adjR2, regr2.R2 = AdjustedRSquare(final_model1, XTest, YTest)
print (regr2.adjR2, regr2.R2)

-0.247839534169 0.792026744305


In [153]:
ErrorMetric(final_model1, XTrain, YTrain)

(15.060888003991582, 19.778325325465481)

In [154]:
ErrorMetric(final_model1, XTest, YTest)

(18.831077871575708, 21.268210339425263)

In [156]:
len(final_model1.coef_!=0)

105

In [157]:
names = [polyfeaturenames[i] for i in list(np.where(final_model1.coef_ != 0.0)[0])]
print(names)

['RM', 'PTRATIO', 'LSTAT', 'CRIM_Square', 'ZN_Square', 'CHAS_Square', 'RM_Square', 'RM_PTRATIO', 'RM_LSTAT', 'B_Square']


In [158]:
len(names)

10

In [159]:
# Conclusion
# lasso model with Alpha = 1 is the best model that minimizes the MAPE between Train and Test set

# Tasks
# Errors in this model:

# convert the RAD into categorical feature before applying poly feature
# polynomial on binary is not applicable, separate the binary feature from the data and apply poly feature
# combine the features
# create cross validated dataset to apply grid search

# Reference Material:
https://www-bcf.usc.edu/~gareth/ISL/ISLR%20First%20Printing.pdf