In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.linear_model import LinearRegression

In [20]:
from sklearn import datasets, linear_model
from scipy import linalg

In [21]:
bhdata = datasets.load_boston()

featuredata = bhdata.data

colnames = bhdata.feature_names

data = pd.DataFrame(featuredata,columns=colnames)
data['target'] = bhdata.target

In [22]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [23]:
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.593761   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.596783   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.647423   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT      target  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [29]:
#split the dataset into training and testig 
data_train, data_test = train_test_split(data,test_size=0.30,random_state=707)

In [26]:
data_train.index, data_test.index

(Int64Index([ 99, 102, 416, 266, 101, 501, 426,  33, 140, 198,
             ...
             279, 177, 143, 152, 372, 204,  53, 294, 211, 303],
            dtype='int64', length=354),
 Int64Index([ 64, 100, 400, 485, 454, 288, 112, 478,  66, 187,
             ...
             305, 492, 300, 234,  90, 314, 287, 384, 108, 338],
            dtype='int64', length=152))

In [30]:
data_train.index, data_test.index

(Int64Index([171, 215,  79, 240,  29, 393, 308, 381,  35,  48,
             ...
              45, 442, 205,  39, 300, 121, 355, 159, 249, 347],
            dtype='int64', length=354),
 Int64Index([  6, 487, 259, 128, 199, 361, 396, 192, 408, 349,
             ...
             207, 410, 453, 131, 212,  51, 168,  59, 278, 326],
            dtype='int64', length=152))

In [25]:
data_train.shape,data_test.shape

((354, 14), (152, 14))

In [31]:
corr = data.corr()
corr

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.200469  0.406583 -0.055892  0.420972 -0.219247  0.352734   
ZN      -0.200469  1.000000 -0.533828 -0.042697 -0.516604  0.311991 -0.569537   
INDUS    0.406583 -0.533828  1.000000  0.062938  0.763651 -0.391676  0.644779   
CHAS    -0.055892 -0.042697  0.062938  1.000000  0.091203  0.091251  0.086518   
NOX      0.420972 -0.516604  0.763651  0.091203  1.000000 -0.302188  0.731470   
RM      -0.219247  0.311991 -0.391676  0.091251 -0.302188  1.000000 -0.240265   
AGE      0.352734 -0.569537  0.644779  0.086518  0.731470 -0.240265  1.000000   
DIS     -0.379670  0.664408 -0.708027 -0.099176 -0.769230  0.205246 -0.747881   
RAD      0.625505 -0.311948  0.595129 -0.007368  0.611441 -0.209847  0.456022   
TAX      0.582764 -0.314563  0.720760 -0.035587  0.668023 -0.292048  0.506456   
PTRATIO  0.289946 -0.391679  0.383248 -0.121515  0.188933 -0.355501  0.261515   
B       -0.385064  0.175520 -0.356977  0.048788 -0.380051  0.128069 -0.273534   
LSTAT    0.455621 -0.412995  0.603800 -0.053929  0.590879 -0.613808  0.602339   
target  -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   

              DIS       RAD       TAX   PTRATIO         B     LSTAT    target  
CRIM    -0.379670  0.625505  0.582764  0.289946 -0.385064  0.455621 -0.388305  
ZN       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445  
INDUS   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725  
CHAS    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260  
NOX     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321  
RM       0.205246 -0.209847 -0.292048 -0.355501  0.128069 -0.613808  0.695360  
AGE     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955  
DIS      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929  
RAD     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626  
TAX     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536  
PTRATIO -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787  
B        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461  
LSTAT   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663  
target   0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000

In [63]:
XTrain = np.array(data_train.iloc[:,0:(data.shape[1]-1)])
YTrain = np.array(data_train['target'])

In [64]:
XTest = np.array(data_test.iloc[:,0:(data.shape[1]-1)])
YTest = np.array(data_test['target'])

In [65]:
XTrain.shape, XTest.shape

((354, 13), (152, 13))

In [66]:
#multiple linear regression model
reg = linear_model.LinearRegression(normalize=True)
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [67]:
reg.fit(XTrain,YTrain) #training the model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [68]:
print('Coefficients: \n', np.round(reg.coef_,0))

Coefficients: 
 [ -0.   0.  -0.   3. -22.   3.   0.  -2.   0.  -0.  -1.   0.  -1.]


In [69]:
print('Coefficients: \n', np.round(reg.intercept_,0))

Coefficients: 
 51.0


In [70]:
reg.score(XTrain,YTrain) # R-square value from the trained model

0.7301247849527104

In [71]:
reg.score(XTest,YTest) # R-square value from the test set

0.7384109847909331

In [72]:
from scipy import stats

In [73]:
#adjusted R square
def AdjustedRSquare(model,X,Y):
    YHat = model.predict(X)
    n,k = X.shape
    sse = np.sum(np.square(YHat-Y),axis=0)
    sst = np.sum(np.square(Y-np.mean(Y)),axis=0)
    R2 = 1- sse/sst
    adjR2 = R2-(1-R2)*(float(k)/(n-k-1))
    return adjR2, R2

In [74]:
def ReturnPValue(model,X,Y):
    YHat = model.predict(X)
    n,k = X.shape
    sse = np.sum(np.square(YHat-Y),axis=0)
    x = np.hstack((np.ones((n,1)),np.matrix(X)))
    df = float(n-k-1)
    sampleVar = sse/df
    sampleVarianceX = x.T*x
    covarianceMatrix = linalg.sqrtm(sampleVar*sampleVarianceX.I)
    se = covarianceMatrix.diagonal()[1:]
    betasTstat = np.zeros(len(se))
    for i in range(len(se)):
        betasTstat[i] = model.coef_[i]/se[i]
    betasPvalue = 1- stats.t.cdf(abs(betasTstat),df)
    return betasPvalue

In [75]:
np.round(ReturnPValue(reg,XTrain,YTrain),2)

array([0.01, 0.  , 0.36, 0.  , 0.  , 0.  , 0.28, 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  ])

In [76]:
reg.adjR2, reg.R2 = AdjustedRSquare(reg,XTrain,YTrain)
print (reg.adjR2, reg.R2)


0.719806026730314 0.7301247849527104


In [77]:
def ErrorMetric(model,X,Y):
    Yhat = model.predict(X)
    MAPE = np.mean(abs(Y-Yhat)/Y)*100
    MSSE = np.mean(np.square(Y-Yhat))
    return MAPE, MSSE

In [78]:
ErrorMetric(reg,XTrain,YTrain)

(16.36106604641107, 21.881688402276126)

In [79]:
ErrorMetric(reg,XTest,YTest)

(17.702494110433914, 24.113264552622116)

In [80]:
alpha = 0.05
erroR = 1

In [81]:
reg.BetasPValue = ReturnPValue(reg,XTrain,YTrain)

In [82]:
MAPE, prevMSSE = ErrorMetric(reg,XTest,YTest)
MAPE, prevMSSE

(17.702494110433914, 24.113264552622116)

In [83]:
while (erroR > 0.001):
    ind = np.where(reg.BetasPValue>alpha)[0]
    if(len(ind)==0):
        ind = np.argmax(reg.BetasPValue)
        
    XTrain = np.delete(XTrain,ind,axis=1)
    XTest = np.delete(XTest,ind,axis=1)
    
    reg.fit(XTrain,YTrain)
    
    reg.BetasPValue = ReturnPValue(reg,XTrain, YTrain)
    MAPE, MSSE = ErrorMetric(reg,XTest,YTest)

    erroR = prevMSSE - MSSE
print (erroR, MSSE)

-0.6760717690443094 24.789336321666426


In [86]:
np.round(reg.score(XTrain,YTrain),2)

0.73

In [87]:
np.round(reg.score(XTest,YTest),2)

0.73

In [89]:
np.round(AdjustedRSquare(reg,XTrain,YTrain),2)

array([0.72, 0.73])

In [90]:
np.round(AdjustedRSquare(reg,XTest,YTest),2)

array([0.71, 0.73])

In [93]:
np.round(reg.coef_,1)

array([  0.1,   2.9, -21.2,   2.6,  -1.8,   0.3,  -0. ,  -1.1,   0. ,
        -0.6])

In [94]:
np.round(reg.intercept_,1)

49.8

# Next Class

In [57]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [51]:
data.RAD.value_counts()

24.0    132
5.0     115
4.0     110
3.0      38
6.0      26
8.0      24
2.0      24
1.0      20
7.0      17
Name: RAD, dtype: int64

In [53]:
RAD_Dummies = pd.get_dummies(data.RAD,prefix='RAD',drop_first=True)

In [55]:
RAD_Dummies.head(10)

RAD_2.0  RAD_3.0  RAD_4.0  RAD_5.0  RAD_6.0  RAD_7.0  RAD_8.0  RAD_24.0
0        0        0        0        0        0        0        0         0
1        1        0        0        0        0        0        0         0
2        1        0        0        0        0        0        0         0
3        0        1        0        0        0        0        0         0
4        0        1        0        0        0        0        0         0
5        0        1        0        0        0        0        0         0
6        0        0        0        1        0        0        0         0
7        0        0        0        1        0        0        0         0
8        0        0        0        1        0        0        0         0
9        0        0        0        1        0        0        0         0

In [57]:
modeldata = pd.concat([data,RAD_Dummies],axis=1)

In [58]:
modeldata.head(2)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   

     ...     LSTAT  target  RAD_2.0  RAD_3.0  RAD_4.0  RAD_5.0  RAD_6.0  \
0    ...      4.98    24.0        0        0        0        0        0   
1    ...      9.14    21.6        1        0        0        0        0   

   RAD_7.0  RAD_8.0  RAD_24.0  
0        0        0         0  
1        0        0         0  

[2 rows x 22 columns]

In [59]:
df_train, df_test = cv.train_test_split(modeldata,test_size=0.30,random_state=1234)

In [60]:
df_train.shape, df_test.shape

((354, 22), (152, 22))

In [61]:
XTrain = df_train.iloc[:,list(range(7)) + list(range(9,13)) + list(range(15,df_train.shape[1]))].as_matrix()
YTrain = df_train['target']

In [62]:
XTest = df_test.iloc[:,list(range(7)) + list(range(9,13)) + list(range(15,df_test.shape[1]))].as_matrix()
YTest = df_test['target']

In [63]:
XTrain.shape,YTrain.shape

((354, 18), (354,))

In [64]:
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [65]:
regr = linear_model.LinearRegression(normalize=True)

In [66]:
regr.fit(XTrain,YTrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [67]:
regr.score(XTrain,YTrain)

0.69555724614189307

In [68]:
regr.MAPE, regr.MSSE = ErrorMetric(regr,XTest,YTest)
regr.MAPE, regr.MSSE

(18.16032205622922, 23.78119544378531)

In [69]:
regr.adjR2, regr.R2 = AdjustedRSquare(regr,XTrain,YTrain)
print (regr.adjR2, regr.R2)

0.6791991280241442 0.6955572461418932


In [70]:
# Polynomial features
# We can try Polynomial Rergession 
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler

In [71]:
scaler = StandardScaler()

In [72]:
X = scaler.fit_transform(bhdata['data'])

In [73]:
pd.DataFrame(X).head()

0         1         2         3         4         5         6   \
0 -0.417713  0.284830 -1.287909 -0.272599 -0.144217  0.413672 -0.120013   
1 -0.415269 -0.487722 -0.593381 -0.272599 -0.740262  0.194274  0.367166   
2 -0.415272 -0.487722 -0.593381 -0.272599 -0.740262  1.282714 -0.265812   
3 -0.414680 -0.487722 -1.306878 -0.272599 -0.835284  1.016303 -0.809889   
4 -0.410409 -0.487722 -1.306878 -0.272599 -0.835284  1.228577 -0.511180   

         7         8         9         10        11        12  
0  0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.075562  
1  0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.492439  
2  0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.208727  
3  1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.361517  
4  1.077737 -0.752922 -1.106115  0.113032  0.441052 -1.026501

In [74]:
poly = PolynomialFeatures(2)

In [75]:
poly

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False)

In [76]:
Xpoly = poly.fit_transform(X)

In [80]:
Xpoly.shape

(506, 105)

In [77]:
print (len(Xpoly))

506


In [78]:
x = Xpoly
Y = bhdata['target']

In [81]:
# interaction features
featurenames = ['intercept'] + list(bhdata['feature_names'])

polyfeaturenames = [];

for i,x in enumerate(featurenames):
    for y in featurenames[i:]:
        if (x == 'intercept'):
            polyfeaturenames.append(y)
        elif (x==y):
            polyfeaturenames.append((y+'_Square'))
        else:
            polyfeaturenames.append((x+'_'+y))

print(featurenames)


['intercept', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']


In [82]:
print (polyfeaturenames)

['intercept', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'CRIM_Square', 'CRIM_ZN', 'CRIM_INDUS', 'CRIM_CHAS', 'CRIM_NOX', 'CRIM_RM', 'CRIM_AGE', 'CRIM_DIS', 'CRIM_RAD', 'CRIM_TAX', 'CRIM_PTRATIO', 'CRIM_B', 'CRIM_LSTAT', 'ZN_Square', 'ZN_INDUS', 'ZN_CHAS', 'ZN_NOX', 'ZN_RM', 'ZN_AGE', 'ZN_DIS', 'ZN_RAD', 'ZN_TAX', 'ZN_PTRATIO', 'ZN_B', 'ZN_LSTAT', 'INDUS_Square', 'INDUS_CHAS', 'INDUS_NOX', 'INDUS_RM', 'INDUS_AGE', 'INDUS_DIS', 'INDUS_RAD', 'INDUS_TAX', 'INDUS_PTRATIO', 'INDUS_B', 'INDUS_LSTAT', 'CHAS_Square', 'CHAS_NOX', 'CHAS_RM', 'CHAS_AGE', 'CHAS_DIS', 'CHAS_RAD', 'CHAS_TAX', 'CHAS_PTRATIO', 'CHAS_B', 'CHAS_LSTAT', 'NOX_Square', 'NOX_RM', 'NOX_AGE', 'NOX_DIS', 'NOX_RAD', 'NOX_TAX', 'NOX_PTRATIO', 'NOX_B', 'NOX_LSTAT', 'RM_Square', 'RM_AGE', 'RM_DIS', 'RM_RAD', 'RM_TAX', 'RM_PTRATIO', 'RM_B', 'RM_LSTAT', 'AGE_Square', 'AGE_DIS', 'AGE_RAD', 'AGE_TAX', 'AGE_PTRATIO', 'AGE_B', 'AGE_LSTAT', 'DIS_Square', 'DIS_RAD', 'DIS_TAX', 'DIS_PTR

In [83]:
Xpoly.shape

(506, 105)

In [84]:
regr2 = linear_model.LinearRegression(normalize=True)

regr2

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [85]:
regr2.fit(Xpoly,Y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [86]:
regr2.score(Xpoly,Y)

0.92913512889272709

In [87]:
regr2.adjR2, regr2.R2 = AdjustedRSquare(regr2,Xpoly,Y)
print (regr2.adjR2, regr2.R2)


0.910533100227 0.929135128893


In [88]:
regr2.MAPE, regr2.MSSE = ErrorMetric(regr2,Xpoly,Y)
print (regr2.MAPE, regr2.MSSE)

9.37570483464 5.98238096594


In [89]:
print (regr.coef_)
print (regr2.coef_)

[ -6.23532988e-02   2.18815262e-02   9.33831537e-02   2.93246737e+00
  -1.12203719e+01   3.08879122e+00   4.38326907e-02  -1.11281058e-02
  -1.19295071e+00   9.35517059e-03  -6.24797151e-01   3.28814392e+00
   1.77814685e+00   1.52238661e+00   1.03030167e+00   1.85835407e+00
   1.95998592e+00   8.04547118e+00]
[  5.18777537e-11   1.55844257e+01   1.47907388e+01   9.43891286e+00
  -2.39884963e+12  -1.87547978e+00   3.51405735e+00  -2.10019705e+00
  -2.48290382e+00   5.06244806e+00  -9.99217020e+00   1.13691270e+00
   1.42704511e+00  -3.16818688e+00   1.31562093e-01   4.27900644e+01
   2.32056203e+01   5.44460534e+00  -7.91824383e-01   7.82013594e-01
  -8.23700001e-01  -1.67958720e+00   1.59429834e+01  -3.45897964e+01
   7.12806513e+00  -2.46659537e-01   1.25171990e+00  -2.61930355e-01
  -7.97082015e-01  -3.76763277e-01  -2.74868520e+00   2.33284676e-01
   2.95491599e-02  -4.96018924e-01  -1.01449457e+00   2.49568080e+00
  -3.48879850e-01   1.35012364e+00  -7.49572500e-01   1.86933832e+0

In [110]:
# Null: beta estimates are = 0
# Alt : beta estimates are != 0

In [111]:
# to restrict the model overfitting
# regularized regression models

# LASSO - L1
# Ridge - L2

In [112]:
from sklearn.linear_model import Lasso

In [113]:
XTrain, XTest, YTrain, YTest = cv.train_test_split(Xpoly,Y, test_size=0.25,random_state=1234)

In [114]:
XTrain.shape, XTest.shape, YTrain.shape, YTest.shape

((379, 105), (127, 105), (379,), (127,))

In [125]:
lassoMod = Lasso(alpha=2)

In [126]:
lassoMod.fit(XTrain,YTrain)

Lasso(alpha=2, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [127]:
print (lassoMod.coef_)

[ 0.         -0.          0.         -0.          0.         -0.
  1.17026498 -0.          0.         -0.         -0.         -0.09892521
  0.         -3.19789261 -0.07078692  0.         -0.          0.         -0.
 -0.         -0.          0.         -0.         -0.          0.          0.
 -0.          0.15665256 -0.          0.         -0.          0.         -0.
  0.         -0.         -0.         -0.          0.         -0.          0.
  0.         -0.         -0.         -0.          0.         -0.         -0.
  0.          0.         -0.          0.15429983 -0.          0.          0.
 -0.          0.          0.          0.          0.         -0.         -0.
 -0.         -0.          0.         -0.         -0.         -0.          0.
 -0.          0.72977841 -0.          0.         -0.         -0.
 -0.59164056  0.         -0.          0.          0.         -0.         -0.
 -0.          0.         -0.         -0.          0.          0.          0.
 -0.          0.         -0

In [128]:
lassoMod.coef_[((lassoMod.coef_)!=0)]

array([ 1.17026498, -0.09892521, -3.19789261, -0.07078692,  0.15665256,
        0.15429983,  0.72977841, -0.59164056, -0.28246009])

In [129]:
lassoMod = Lasso(alpha=1)
lassoMod.fit(XTrain,YTrain)
print (lassoMod.coef_)

[ 0.         -0.          0.         -0.          0.         -0.
  1.56671904 -0.         -0.         -0.         -0.         -0.65869171
  0.         -3.84587689 -0.07509719  0.         -0.          0.         -0.
 -0.         -0.          0.         -0.         -0.          0.          0.
 -0.          0.06358342 -0.          0.          0.          0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.          0.
  0.         -0.         -0.         -0.          0.         -0.         -0.
  0.          0.         -0.          0.19172068 -0.         -0.          0.
 -0.          0.          0.          0.          0.         -0.         -0.
 -0.         -0.          0.         -0.         -0.         -0.          0.
 -0.          0.77646759 -0.          0.         -0.         -0.
 -0.99781114  0.         -0.12441185  0.          0.         -0.         -0.
 -0.          0.         -0.         -0.          0.          0.          0.
 -0.          0.         -0

In [130]:
lassoMod.coef_[((lassoMod.coef_)!=0)]

array([ 1.56671904, -0.65869171, -3.84587689, -0.07509719,  0.06358342,
        0.19172068,  0.77646759, -0.99781114, -0.12441185, -0.26430648])

In [131]:
names = [polyfeaturenames[i] for i in list(np.where(lassoMod.coef_ != 0.0)[0])]
names

['RM',
 'PTRATIO',
 'LSTAT',
 'CRIM_Square',
 'ZN_Square',
 'CHAS_Square',
 'RM_Square',
 'RM_PTRATIO',
 'RM_LSTAT',
 'B_Square']

In [132]:
lassoMod.MAPE, lassoMod.MSSE = ErrorMetric(lassoMod, XTrain, YTrain)

In [133]:
print (lassoMod.MAPE, lassoMod.MSSE)

15.060888004 19.7783253255


In [134]:
lassoMod.MAPE, lassoMod.MSSE = ErrorMetric(lassoMod, XTest, YTest)

In [135]:
print (lassoMod.MAPE, lassoMod.MSSE)

18.8310778716 21.2682103394


In [136]:
from sklearn.linear_model import Ridge


In [138]:
ridgeMod1 = Ridge(alpha=1)
ridgeMod1.fit(XTrain,YTrain)
names = [polyfeaturenames[i] for i in list(np.where(ridgeMod1.coef_ != 0.0)[0])]
print(names)
ridgeMod1.MAPE, ridgeMod1.MSSE = ErrorMetric(ridgeMod1, XTrain, YTrain)
print (ridgeMod1.MAPE, ridgeMod1.MSSE)


['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'CRIM_Square', 'CRIM_ZN', 'CRIM_INDUS', 'CRIM_CHAS', 'CRIM_NOX', 'CRIM_RM', 'CRIM_AGE', 'CRIM_DIS', 'CRIM_RAD', 'CRIM_TAX', 'CRIM_PTRATIO', 'CRIM_B', 'CRIM_LSTAT', 'ZN_Square', 'ZN_INDUS', 'ZN_CHAS', 'ZN_NOX', 'ZN_RM', 'ZN_AGE', 'ZN_DIS', 'ZN_RAD', 'ZN_TAX', 'ZN_PTRATIO', 'ZN_B', 'ZN_LSTAT', 'INDUS_Square', 'INDUS_CHAS', 'INDUS_NOX', 'INDUS_RM', 'INDUS_AGE', 'INDUS_DIS', 'INDUS_RAD', 'INDUS_TAX', 'INDUS_PTRATIO', 'INDUS_B', 'INDUS_LSTAT', 'CHAS_Square', 'CHAS_NOX', 'CHAS_RM', 'CHAS_AGE', 'CHAS_DIS', 'CHAS_RAD', 'CHAS_TAX', 'CHAS_PTRATIO', 'CHAS_B', 'CHAS_LSTAT', 'NOX_Square', 'NOX_RM', 'NOX_AGE', 'NOX_DIS', 'NOX_RAD', 'NOX_TAX', 'NOX_PTRATIO', 'NOX_B', 'NOX_LSTAT', 'RM_Square', 'RM_AGE', 'RM_DIS', 'RM_RAD', 'RM_TAX', 'RM_PTRATIO', 'RM_B', 'RM_LSTAT', 'AGE_Square', 'AGE_DIS', 'AGE_RAD', 'AGE_TAX', 'AGE_PTRATIO', 'AGE_B', 'AGE_LSTAT', 'DIS_Square', 'DIS_RAD', 'DIS_TAX', 'DIS_PTRATIO', 'DIS_B

In [149]:
ridgeMod1 = Ridge(alpha=0)
ridgeMod1.fit(XTrain,YTrain)
names = [polyfeaturenames[i] for i in list(np.where(ridgeMod1.coef_ != 0.0)[0])]
print(names)
ridgeMod1.MAPE, ridgeMod1.MSSE = ErrorMetric(ridgeMod1, XTrain, YTrain)
print (ridgeMod1.MAPE, ridgeMod1.MSSE)


['intercept', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'CRIM_Square', 'CRIM_ZN', 'CRIM_INDUS', 'CRIM_CHAS', 'CRIM_NOX', 'CRIM_RM', 'CRIM_AGE', 'CRIM_DIS', 'CRIM_RAD', 'CRIM_TAX', 'CRIM_PTRATIO', 'CRIM_B', 'CRIM_LSTAT', 'ZN_Square', 'ZN_INDUS', 'ZN_CHAS', 'ZN_NOX', 'ZN_RM', 'ZN_AGE', 'ZN_DIS', 'ZN_RAD', 'ZN_TAX', 'ZN_PTRATIO', 'ZN_B', 'ZN_LSTAT', 'INDUS_Square', 'INDUS_CHAS', 'INDUS_NOX', 'INDUS_RM', 'INDUS_AGE', 'INDUS_DIS', 'INDUS_RAD', 'INDUS_TAX', 'INDUS_PTRATIO', 'INDUS_B', 'INDUS_LSTAT', 'CHAS_Square', 'CHAS_NOX', 'CHAS_RM', 'CHAS_AGE', 'CHAS_DIS', 'CHAS_RAD', 'CHAS_TAX', 'CHAS_PTRATIO', 'CHAS_B', 'CHAS_LSTAT', 'NOX_Square', 'NOX_RM', 'NOX_AGE', 'NOX_DIS', 'NOX_RAD', 'NOX_TAX', 'NOX_PTRATIO', 'NOX_B', 'NOX_LSTAT', 'RM_Square', 'RM_AGE', 'RM_DIS', 'RM_RAD', 'RM_TAX', 'RM_PTRATIO', 'RM_B', 'RM_LSTAT', 'AGE_Square', 'AGE_DIS', 'AGE_RAD', 'AGE_TAX', 'AGE_PTRATIO', 'AGE_B', 'AGE_LSTAT', 'DIS_Square', 'DIS_RAD', 'DIS_TAX', 'DIS_PTR

In [150]:
from sklearn.grid_search import GridSearchCV

In [151]:
XTrain, XTest, YTrain, YTest = cv.train_test_split(Xpoly,Y, test_size=0.25,random_state=1234)

In [152]:
XTrain.shape, XTest.shape, YTrain.shape, YTest.shape

((379, 105), (127, 105), (379,), (127,))

In [153]:
from sklearn.cross_validation import ShuffleSplit

In [154]:
from sklearn.metrics import r2_score

In [162]:
def performance_metric(y_true, y_predict):
    score = r2_score(y_true, y_predict)
    return score

In [163]:
from sklearn.metrics import make_scorer

In [188]:
def fit_model(X,y):
    cv_sets = ShuffleSplit(XTrain.shape[0],n_iter=10,test_size=0.20,random_state=1234)
    ridgeModel = Ridge()
    params = {'alpha':list(range(0,11)),
             'solver' : ('auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga')}
    scoring_func = make_scorer(performance_metric)
    grid = GridSearchCV(ridgeModel,params,scoring_func,cv=cv_sets)
    grid = grid.fit(X,y)
    return grid.best_estimator_

In [189]:
fit_model(XTrain,YTrain)

Ridge(alpha=4, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='lsqr', tol=0.001)

In [172]:
final_model = fit_model(XTrain,YTrain)

In [178]:
ErrorMetric(final_model, XTrain, YTrain)

(9.1106619257527619, 5.9231181889032207)

In [179]:
ErrorMetric(final_model, XTest, YTest)

(13.128549557729343, 10.805728603275506)

In [180]:
regr2.adjR2, regr2.R2 = AdjustedRSquare(final_model, XTrain, YTrain)
print (regr2.adjR2, regr2.R2)

0.895305003719 0.92438694713


In [181]:
regr2.adjR2, regr2.R2 = AdjustedRSquare(final_model, XTest, YTest)
print (regr2.adjR2, regr2.R2)

0.366010814663 0.894335135777


In [182]:
final_model.coef_

array([ 0.        ,  0.01337066,  0.13275668,  0.58016989,  0.12735482,
       -1.13241814,  3.02645627, -1.35748299, -2.41796659,  1.11973246,
       -1.28828649, -0.35743753,  0.52332541, -3.58363057,  0.09872345,
       -0.01178421,  0.04997743,  2.31704452, -0.62783432,  0.86190811,
        0.09861108,  0.11017284, -1.04124546,  0.21469322, -0.28498659,
       -0.23143359,  0.5628247 ,  0.03999252,  0.15590942,  0.00525088,
       -0.20629951,  0.33570623, -0.15936202, -0.39634774, -0.27875563,
        1.44784316,  0.0156192 ,  0.36099164, -0.49684816,  0.94813938,
        0.52578319,  1.33285452,  0.70932829,  0.30211382,  0.57630283,
        0.13946419, -0.00365214, -0.53806854,  0.40828201, -0.71230954,
        0.43247141, -1.28767841, -1.16426499,  0.43356713,  0.70940143,
        0.01615991,  0.88556972, -0.55905785, -0.12272527, -0.60916281,
       -0.4041514 ,  0.38114505, -0.87260455,  1.30812643, -1.28483548,
        0.59860041, -0.61030623, -0.06637178,  0.94963465,  0.11

In [184]:
XTrain.shape

(379, 105)